# Generated by Django 5.2.17 on 2026-09-21 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('genero_categoria', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_venta', models.DateField()),
                ('forma_de_pago', models.CharField(max_length=25)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.usuarios')),
            ],
        ),
    ]
