# Generated by Django 5.2.17 on 2026-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Libros',
        ),
        migrations.DeleteModel(
            name='Ventas_detalles',
        ),
    ]
